name: libpythonproLEE-CI

on: [ pull_request ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.10.2
    - uses: actions/setup-python@v2
    - with:
        python-version: 3.10.2
    - name: Install dependencies
      run: |
      pip install pipenv codecov
      pipenv sync --dev
    - name: Lint with flake8
      run: |
      flake8 .

    - name: Test with pytest
      run: pytest libpythonpro --cov=libpythonpro

    - name: Posting Coverage
      run: pipenv run codecov