name: libpythonproLEE-CI

on: [ push ]

jobs:
  build:
    env:
      GITHUB_TOKEN:  bd4152ce-86b3-4deb-8383-02adee5c6a60

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.10.2
    - uses: actions/setup-python@v2
    - with:
        python-version: 3.10.2

    - name: Install dependencies
      run: |
      pip install pipenv codecov
      pipenv sync --dev

    - name: Lint with flake8
      run: |
      flake8 .

    - name: Test with pytest
      run: pytest libpythonpro --cov=libpythonpro

    - name: Posting Coverage
      run: pipenv run codecov

    - name: Coverage Report
      env:
        CODECOV_TOKEN: bd4152ce-86b3-4deb-8383-02adee5c6a60
      run: |
        codecov