name: libpythonproLEE-CI

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10.2
    - uses: actions/setup-python@v2
    - with:
        python-version: 3.10.2
    - name: Install dependencies
      run: |
      python -m pip install --upgrade pip
      pip install -r requeriments-dev.txt
    - name: Lint with flake8
      run: |
      flake8 .